server:
  port: 8002
  servlet:
    context-path: /
    tomcat:
      accesslog:
        enabled: true
        pattern: '%h %l %u %t "%r" %s %D %b "%{Referer}i" "%{User-Agent}i" "%{traceId}r" "%{rt_code}r"'
        directory: ${BASE_LOG_HOME:/data/tomcat}/logs

spring:
  datasource:
    data-username: root
    data-password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&serverTimezone=UTC

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.zhy.po