server:
  port: 8003
  servlet:
    context-path: /
    tomcat:
      accesslog:
        enabled: true
        pattern: '%h %l %u %t "%r" %s %D %b "%{Referer}i" "%{User-Agent}i" "%{traceId}r" "%{rt_code}r"'
        directory: ${BASE_LOG_HOME:/data/tomcat}/logs

spring:
  datasource:
    data-username: root
    data-password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&serverTimezone=UTC

mybatis:
  mapper-locations: classpath:mybatis/mapper/*/*.xml
  type-aliases-package: mybatis.po
  config-location: classpath:mybatis-config.xml